# la_neighborhoods.py
LA_CITY_NEIGHBORHOODS = {
    'angelino heights', 'arroyo view estates', 'arts district', 'atwater village', 'baldwin hills',
    'baldwin village', 'bel air', 'beverly crest', 'beverly glen', 'beverlywood', 'boeing',
    'boyle heights', 'brentwood', 'cadillac-corning', 'cahuenga pass', 'canoga park', 'carthay',
    'carthay circle', 'century city', 'century palms', 'chatsworth', 'cheviot hills', 'chinatown',
    'cypress park', 'del rey', 'downtown', 'eagle rock', 'echo park', 'el sereno', 'elysian park',
    'elysian valley', 'encino', 'faircrest heights', 'figueroa park square', 'glassell park',
    'gramercy place', 'granada hills', 'hancock park', 'harbor city', 'harbor gateway', 'harbor pines',
    'harvard heights', 'harvard park', 'highland park', 'historic filipinotown', 'hollywood',
    'hollywood hills', 'hollywood hills west', 'hyde park', 'jefferson park', 'koreatown',
    'ladera heights', 'lake balboa', 'lakeview terrace', 'leimert park', 'lincoln heights',
    'little tokyo', 'los feliz', 'los angeles', 'manchester square', 'mar vista', 'mid-city',
    'miracle mile', 'mission hills', 'mt. washington', 'north hills', 'north hollywood',
    'northridge', 'pacific palisades', 'pacoima', 'palms', 'panorama city', 'pico-union',
    'playa del rey', 'playa vista', 'porter ranch', 'rancho park', 'reseda', 'san pedro',
    'sawtelle', 'shadow hills', 'sherman oaks', 'silver lake', 'studio city', 'sun valley',
    'sunland', 'sylmar', 'tarzana', 'terminal island', 'tujunga', 'valley glen', 'valley village',
    'van nuys', 'venice', 'vernon central', 'west adams', 'west hills', 'west los angeles',
    'westchester', 'westlake', 'westwood', 'wilmington', 'wilshire center', 'winnetka',
    'woodland hills', 'adams-normandie', 'arlington heights', 'arlington park', 'byzantine-latino quarter',
    'central', 'central-alameda', 'central city', 'cloverdale/cochran', 'country club park',
    'crenshaw', 'crenshaw district', 'east hollywood', 'exposition park', 'exposition',
    'florence-firestone', 'green meadows', 'hermon', 'lafayette square', 'longwood',
    'mandeville canyon', 'marina peninsula', 'melrose', 'palisades highlands',
    'park la brea', 'picfair village', 'pico park', 'rampart village', 'regent square',
    'reseda ranch', 'rey nier village', 'sycamore square', 'thai town', 'toluca lake',
    'toluca terrace', 'toluca woods', 'university hills', 'university park',
    'vermont knolls', 'vermont square', 'vermont vista', 'victoria park', 'watts',
    'wellington square', 'west vernon', 'wholesale district'
}